name: Discord Notification
on: push

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send to Discord
        run: curl -X POST -H "Content-Type: application/json" -d "{\"content\": \"🚀 Nouveau push par ${{ github.actor }}\nMessage: ${{ github.event.head_commit.message }}\"}" ${{ secrets.DISCORD_WEBHOOK }}
