- name: Send Discord notification
        if: ${{ github.event_name == 'push' }}
        run: |
          curl -H "Content-Type: application/json" \
          -d '{"content": "🖼️ Nouvelle image ajoutée par ${{ github.actor }}", "embeds": [{"title": "Image Uploadée", "description": "Fichier ajouté dans /image/", "color": 5814783}]}' \
          ${{ secrets.DISCORD_WEBHOOK }}
